apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ${values:name}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: ${values:port}
      name: http
      protocol: HTTP
    hosts:
    - "*"
