# package.json
package: ${file(../package.json)}

# Service values
values:
  # Service name
  name: ${self:package.name}
  version: ${self:package.version}

  # Istio subset name
  subset: v${replace(${self:values.version},/\./gi,-)}

  # Deployment name
  deployment: ${self:values.name}-${self:values.subset}

  description: ${self:package.description}

  env: ${global:env}

  # Service port
  port: 80
  containerPort: 80
  # App port
  targetPort: ${self:package.port}
  replicas: 1
  # App docker image configuration
  image:
    # Name of the docker repository
    repository: ${self:package.dockerRepository}
    # Setting tasg as git commit hash
    tag: ${git:sha1}
    pullPolicy: Always
  serviceAccount: ${self:values.deployment}-service-account

# Service configuration
service:
  # Kubernetes minifests output folder 
  output: .build
  
  # Aggregated values. Following array will be reduced to an object
  values: ${merge(${self:values},${global:values})}
  
  # Kubernetes resources
  resources: ${file(./resources/index.yml)}
